import type {
  ExperimentBundle,
  ProfileBundle,
  SourceReference,
} from './types';

import {
  CASE9_ACCESS_BASELINE_BUNDLE,
  CASE9_ACCESS_DEFAULT_EXP,
  CASE9_DAPS_BASELINE_BUNDLE,
  CASE9_DAPS_DEFAULT_EXP,
  CASE9_DAPS_SHOWCASE_BUNDLE,
  CASE9_DAPS_SHOWCASE_DEFAULT_EXP,
  SINR_ELEVATION_REPRODUCTION_BUNDLE,
  SINR_ELEVATION_DEFAULT_EXP,
  TIMER_CHO_REPRODUCTION_BUNDLE,
  TIMER_CHO_DEFAULT_EXP,
} from './defaults-access';
import {
  HOBS_MULTIBEAM_BASELINE_BUNDLE,
  HOBS_MULTIBEAM_DEFAULT_EXP,
  HOBS_REPRODUCTION_BUNDLE,
  HOBS_REPRODUCTION_DEFAULT_EXP,
  HOBS_TR38811_RESEARCH_BUNDLE,
  HOBS_TR38811_RESEARCH_DEFAULT_EXP,
} from './defaults-hobs';
import {
  MODQN_PAPER_BASELINE_BUNDLE,
  MODQN_PAPER_BASELINE_DEFAULT_EXP,
} from './defaults-modqn';
import {
  BH_RESOURCE_BASELINE_BUNDLE,
  BH_RESOURCE_DEFAULT_EXP,
  BH_RESOURCE_ENERGY_PROOF_BUNDLE,
  BH_RESOURCE_ENERGY_PROOF_EXP,
  BH_PF_BASELINE_BUNDLE,
  BH_PF_DEFAULT_EXP,
  BH_SINR_GREEDY_BASELINE_BUNDLE,
  BH_SINR_GREEDY_DEFAULT_EXP,
} from './defaults-bh';
import {
  REAL_TRACE_VALIDATION_BUNDLE,
  REAL_TRACE_DEFAULT_EXP,
  MEO_CONSTELLATION_BASELINE_BUNDLE,
  MEO_CONSTELLATION_DEFAULT_EXP,
  GEO_RELAY_BASELINE_BUNDLE,
  GEO_RELAY_DEFAULT_EXP,
  REALISTIC_FIRST_SCREEN_BUNDLE,
  REALISTIC_FIRST_SCREEN_DEFAULT_EXP,
} from './defaults-misc';

export interface ProfileAuthoringEntry {
  id: string;
  bundle: ProfileBundle;
  exp: ExperimentBundle;
  sourceMap: SourceReference[];
}

export const PROFILE_AUTHORING_ENTRIES: ProfileAuthoringEntry[] = [
  { id: CASE9_ACCESS_BASELINE_BUNDLE.id, bundle: CASE9_ACCESS_BASELINE_BUNDLE, exp: CASE9_ACCESS_DEFAULT_EXP, sourceMap: CASE9_ACCESS_BASELINE_BUNDLE.sourceMap },
  { id: HOBS_MULTIBEAM_BASELINE_BUNDLE.id, bundle: HOBS_MULTIBEAM_BASELINE_BUNDLE, exp: HOBS_MULTIBEAM_DEFAULT_EXP, sourceMap: HOBS_MULTIBEAM_BASELINE_BUNDLE.sourceMap },
  { id: MODQN_PAPER_BASELINE_BUNDLE.id, bundle: MODQN_PAPER_BASELINE_BUNDLE, exp: MODQN_PAPER_BASELINE_DEFAULT_EXP, sourceMap: MODQN_PAPER_BASELINE_BUNDLE.sourceMap },
  { id: BH_RESOURCE_BASELINE_BUNDLE.id, bundle: BH_RESOURCE_BASELINE_BUNDLE, exp: BH_RESOURCE_DEFAULT_EXP, sourceMap: BH_RESOURCE_BASELINE_BUNDLE.sourceMap },
  { id: BH_RESOURCE_ENERGY_PROOF_BUNDLE.id, bundle: BH_RESOURCE_ENERGY_PROOF_BUNDLE, exp: BH_RESOURCE_ENERGY_PROOF_EXP, sourceMap: BH_RESOURCE_ENERGY_PROOF_BUNDLE.sourceMap },
  { id: BH_PF_BASELINE_BUNDLE.id, bundle: BH_PF_BASELINE_BUNDLE, exp: BH_PF_DEFAULT_EXP, sourceMap: BH_PF_BASELINE_BUNDLE.sourceMap },
  { id: BH_SINR_GREEDY_BASELINE_BUNDLE.id, bundle: BH_SINR_GREEDY_BASELINE_BUNDLE, exp: BH_SINR_GREEDY_DEFAULT_EXP, sourceMap: BH_SINR_GREEDY_BASELINE_BUNDLE.sourceMap },
  { id: REAL_TRACE_VALIDATION_BUNDLE.id, bundle: REAL_TRACE_VALIDATION_BUNDLE, exp: REAL_TRACE_DEFAULT_EXP, sourceMap: REAL_TRACE_VALIDATION_BUNDLE.sourceMap },
  { id: CASE9_DAPS_BASELINE_BUNDLE.id, bundle: CASE9_DAPS_BASELINE_BUNDLE, exp: CASE9_DAPS_DEFAULT_EXP, sourceMap: CASE9_DAPS_BASELINE_BUNDLE.sourceMap },
  { id: CASE9_DAPS_SHOWCASE_BUNDLE.id, bundle: CASE9_DAPS_SHOWCASE_BUNDLE, exp: CASE9_DAPS_SHOWCASE_DEFAULT_EXP, sourceMap: CASE9_DAPS_SHOWCASE_BUNDLE.sourceMap },
  { id: MEO_CONSTELLATION_BASELINE_BUNDLE.id, bundle: MEO_CONSTELLATION_BASELINE_BUNDLE, exp: MEO_CONSTELLATION_DEFAULT_EXP, sourceMap: MEO_CONSTELLATION_BASELINE_BUNDLE.sourceMap },
  { id: GEO_RELAY_BASELINE_BUNDLE.id, bundle: GEO_RELAY_BASELINE_BUNDLE, exp: GEO_RELAY_DEFAULT_EXP, sourceMap: GEO_RELAY_BASELINE_BUNDLE.sourceMap },
  { id: SINR_ELEVATION_REPRODUCTION_BUNDLE.id, bundle: SINR_ELEVATION_REPRODUCTION_BUNDLE, exp: SINR_ELEVATION_DEFAULT_EXP, sourceMap: SINR_ELEVATION_REPRODUCTION_BUNDLE.sourceMap },
  { id: HOBS_REPRODUCTION_BUNDLE.id, bundle: HOBS_REPRODUCTION_BUNDLE, exp: HOBS_REPRODUCTION_DEFAULT_EXP, sourceMap: HOBS_REPRODUCTION_BUNDLE.sourceMap },
  { id: HOBS_TR38811_RESEARCH_BUNDLE.id, bundle: HOBS_TR38811_RESEARCH_BUNDLE, exp: HOBS_TR38811_RESEARCH_DEFAULT_EXP, sourceMap: HOBS_TR38811_RESEARCH_BUNDLE.sourceMap },
  { id: TIMER_CHO_REPRODUCTION_BUNDLE.id, bundle: TIMER_CHO_REPRODUCTION_BUNDLE, exp: TIMER_CHO_DEFAULT_EXP, sourceMap: TIMER_CHO_REPRODUCTION_BUNDLE.sourceMap },
  { id: REALISTIC_FIRST_SCREEN_BUNDLE.id, bundle: REALISTIC_FIRST_SCREEN_BUNDLE, exp: REALISTIC_FIRST_SCREEN_DEFAULT_EXP, sourceMap: REALISTIC_FIRST_SCREEN_BUNDLE.sourceMap },
];

export const PROFILE_AUTHORING_REGISTRY: Record<string, ProfileAuthoringEntry> = Object.fromEntries(
  PROFILE_AUTHORING_ENTRIES.map((entry) => [entry.id, entry]),
);

export function getProfileAuthoringEntry(profileId: string): ProfileAuthoringEntry {
  const entry = PROFILE_AUTHORING_REGISTRY[profileId];
  if (!entry) {
    const known = Object.keys(PROFILE_AUTHORING_REGISTRY).join(', ');
    throw new Error(`Unknown authoring profile "${profileId}". Known profiles: ${known}`);
  }
  return entry;
}
